"""create paper_trades

Revision ID: 440891a3f2c1
Revises:
Create Date: 2026-10-04 21:49:03.723075

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "440891a3f2c1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_trades",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("system_version", sa.String(length=32), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("signal_date", sa.Date(), nullable=False),
        sa.Column("exit_date", sa.Date(), nullable=False),
        sa.Column("holding_days", sa.Integer(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum("BUY", "SELL", "HOLD", "AVOID", name="decision_label"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("exit_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("forward_return", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name="ck_confidence_range"),
        sa.CheckConstraint("holding_days > 0", name="ck_holding_days_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ticker", "signal_date", "system_version", name="uq_paper_trade_signal"
        ),
    )
    op.create_index(
        "ix_paper_trades_exit_date", "paper_trades", ["exit_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_paper_trades_exit_date", table_name="paper_trades")
    op.drop_table("paper_trades")
    sa.Enum(name="decision_label").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
